### ISSUE TITLE
v0.4.0 loop icon broken?

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#117]
<img width="687" alt="Screen Shot 2022-05-07 at 1 44 52 PM" src="https://user-images.githubusercontent.com/2731744/167265746-6070a3f5-2dc8-42c0-9da0-02fd99b3466e.png">

**Comment by whatSocks** [comment]
Also confused as to what the three loop-looking icons do

**Comment by simonv3** [comment]
Ah, there should be only one. 

The first one is the one that comes with the player, I thought I had hidden that one. The second one is the one I added. You can toggle between no loop, loop the single track, and loop the entire playlist. The third icon is shuffle.

**Comment by simonv3** [comment]
> The Looping/Shuffle buttons on the bottom bar, to the right, slightly overlap each other. 

Reported here https://community.resonate.is/t/beam-a-native-app-for-linux-macos-and-windows-testing-please/2909/19

**Comment by simonv3** [comment]
I put in a fix to hide one of the loop icons. Let me know if that clarifies things @whatSocks
