### ISSUE TITLE
v0.4.0 tapping shuffle button restarts current track

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#118]
v0.4.0
<img width="662" alt="Screen Shot 2022-05-07 at 1 47 07 PM" src="https://user-images.githubusercontent.com/2731744/167265820-0055f623-ce5e-4279-a60a-c7cefe4a7a38.png">

**Comment by whatSocks** [comment]
it doesn't restart the track, now it starts on a new track from the shuffled list

**Comment by simonv3** [comment]
@whatSocks I'm guessing you expect it to continue playing the current song, and to shuffle all the "next" songs, right?
