### ISSUE TITLE
v0.4.0 Share text excapes UI

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#119]
<img width="754" alt="Screen Shot 2022-05-07 at 1 48 14 PM" src="https://user-images.githubusercontent.com/2731744/167265857-f34579e8-2753-4b51-9752-205319a3934e.png">

somewhat mis-matched expecation - I also sorta expected the share to allow me to easily share a link to download the app

**Comment by acharbonnet** [comment]
![Screen Shot 2022-05-08 at 6 34 26 PM](https://user-images.githubusercontent.com/65929869/167322567-cfc88a0b-3fd8-47bc-9be6-d2b82946b6c7.png)
Hi! I found this working solution to the overflow problem, but the scroll bar runs into the copy button. I thought it might be better if the copy button were moved up and to the right of "Embed Code" as a prettier solution. 

![Screen Shot 2022-05-08 at 6 40 26 PM](https://user-images.githubusercontent.com/65929869/167322860-35258ba0-4b91-4046-9e15-c30147038d68.png)
I also tried hiding the overflow text which doesn't look too bad.
 
What do you think? If you like either solution I can go ahead and open a pull request. If you prefer a different solution, let me know about what you're looking for and I can get started on it tomorrow.

**Comment by simonv3** [comment]
This is great! Thanks @acharbonnet !!

I think either solution works, and I think your suggestion of moving the copy button makes sense too. I'm happy with whichever you decide :)

**Comment by acharbonnet** [comment]
Awesome I'll get it done!

**Comment by acharbonnet** [comment]
![Screen Shot 2022-05-09 at 6 13 14 PM](https://user-images.githubusercontent.com/65929869/167518241-3f5fd83f-f9ce-4f0c-a654-d2d0e3944d54.png)
Here's what I've got! Look good?

**Comment by simonv3** [comment]
Looks great! Merged your PR :)
