### ISSUE TITLE
v0.4.0 Album is missing on release? 

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#120]
<img width="1130" alt="Screen Shot 2022-05-07 at 1 59 47 PM" src="https://user-images.githubusercontent.com/2731744/167266278-2cfc3177-4f70-497d-b528-b46ff33d4b0e.png">

Album is empty but how is this possible

**Comment by simonv3** [comment]
Yeah this is a problem with the v2 api. I haven't yet tested if it's an issue with v3 yet. Existing issue here https://github.com/simonv3/beam/issues/1
