### ISSUE TITLE
v0.4.0 can't exit playlist edit mode

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#122]
- select playlist
- select edit
- in the left menu, tap another playlist

expected: edit goes away and presents me the info about the other playlist
actual: edit of first playlist is still there

In the image I have selected TopShelf but Ampled Artists still appears in the edit 

<img width="1450" alt="Screen Shot 2022-05-07 at 2 03 09 PM" src="https://user-images.githubusercontent.com/2731744/167266396-675d4bd2-4562-4ca6-8c4a-94018a78ca78.png">

**Comment by whatSocks** [comment]
still an issue - 
have 2 playlists, playlist1 and playlist2

* tap playlist1 edit
* in the side menu, tap another playlist2
* edit the title (which is playlist1s title)

this overwrites playlist2 title with the new version of playlist1's title

**Comment by simonv3** [comment]
Oh interesting. I guess it maintains the state of the editing, and that should be changed when the playlist changes. 

This probably requires a change in the Playlist view, where a React.useEffect watches for the playlist changing and then resets the editing boolean to false.
