### ISSUE TITLE
v0.4.0 New Playlist creation fails silently

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#123]
- enter new playlist name in new playlist
- press + button

expected: something happens
actual: nothing happens?

**Comment by whatSocks** [comment]
oh looks like the playlist is there just hard to see: 

<img width="308" alt="Screen Shot 2022-05-07 at 2 19 18 PM" src="https://user-images.githubusercontent.com/2731744/167266874-aef1b04f-b3c0-4a20-8112-5296847f483c.png">

**Comment by simonv3** [comment]
Oh okay so there's probably to things going on here:

1. Creating a playlist needs some sort of "success" pop-up
2. there needs to be scrolling on the left hand side. I don't have that many playlists so I hadn't noticed that.

**Comment by simonv3** [comment]
Put in a fix for this for now, but I still have to think about global state management here a bit. 

Right now we don't store the playlists in a global state, and I'm not sure we should, but if you add a playlist through the pop-up, the playlists on the left hand side of the library don't get updated.

**Comment by simonv3** [comment]
Okay, #143 should now make sure that when a new playlist gets added in the pop up, it shows in the sidebar

**Comment by whatSocks** [comment]
testing: 
http://localhost:8080/library/tag/dream-pop 

tap an item's 3-dot menu, tap "+ Add to playlist"
Enter title for new playlist
Success message pops up
Playlist (eventually) appears in the list

expected: playlist has some tracks in it
actual: playlist is empty

**Comment by simonv3** [comment]
Ah, I guess that's a UX question. When I made this I was thinking that the user will create the playlist and then manually add the song to the playlist, but it sounds like you're expecting it to automatically add the song, and then close the pop up?
