### ISSUE TITLE
Add instructions on installing yarn to README

### ISSUE THREAD

**Issue by simonv3** [simonv3/beam#137]
```
npx install yarn
```

or https://yarnpkg.com/getting-started/install

**Comment by auggod** [comment]
I think, you mean `npx yarn install`

**Comment by simonv3** [comment]
I guess I'm confused about what the intent is, is the intent to to tell someone to install yarn or is it for how to tell people to manage packages? 

For managing packages I think people should just use `yarn` directly without using something like `npx` to preceed it because otherwise they'll have to change all instructions for using any library to use `npx`. Seems to me like the solution is to have folks install yarn directly rather than running it through `npx`? 

(following yarn's [own best practices](https://yarnpkg.com/getting-started/install))

**Comment by peterklingelhofer** [comment]
Right, we already have `yarn install` in the Readme. This issue is to get users to be able to install yarn on their machines if they don't yet have it, I think.

**Comment by auggod** [comment]
Got it. I just wanted to run yarn once.
