### ISSUE TITLE
artist ids missing on label page 

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#142]
testing on d246ec5 
artist ids missing on label page 

http://localhost:8080/library/label/4088 
<img width="798" alt="Screen Shot 2022-05-12 at 4 23 16 PM" src="https://user-images.githubusercontent.com/2731744/168161586-dee8cf2e-3070-4c32-b28b-a1806c2679d2.png">

http://localhost:8080/library/artist/undefined

**Comment by simonv3** [comment]
This is an API issue https://github.com/resonatecoop/tracks-api/issues/26

**Comment by whatSocks** [comment]
Fixed
