### ISSUE TITLE
case on tags

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#144]
http://localhost:8080/library/tag/neoclassical 

<img width="1007" alt="Screen Shot 2022-05-13 at 9 54 05 AM" src="https://user-images.githubusercontent.com/2731744/168298787-dcb9f1bb-ce21-485a-af44-80bb348a3443.png">

Tap on Neoclassical

http://localhost:8080/library/tag/Neoclassical

<img width="989" alt="Screen Shot 2022-05-13 at 9 54 29 AM" src="https://user-images.githubusercontent.com/2731744/168298840-ba262d42-92ce-4b8f-9f93-3aea242bb659.png">

perhaps solution is to lowercase?

**Comment by simonv3** [comment]
Yeah, for the moment, since it looks like the API returns both `Neoclassical` and `neoclassical` results when asking for the lowercase, let's make the query default to search on lowercase, no matter what the capitalization in the URL.
