### ISSUE TITLE
Change artists list order to by id (descending)

### ISSUE THREAD

**Issue by auggod** [simonv3/beam#169]
The api endpoint: https://stream.resonate.coop/api/v3/artists/?limit=50&orderBy=id&order=desc&page=1

**Comment by simonv3** [comment]
Is this an issue on the latest 0.5.2? 

https://github.com/simonv3/beam/blob/main/src/components/Explore/Artists.tsx#L14

These look like the latest artists

![image](https://user-images.githubusercontent.com/485583/184546148-54b9e00e-638d-4245-b69e-5edd7a3eff37.png)

**Comment by auggod** [comment]
Oh, I was not running 0.5.2 even after installing it. I am now, but I can't login.
