### ISSUE TITLE
Incorrect images

### ISSUE THREAD

**Issue by glottis0q** [simonv3/beam#172]
Version 0.5.2
OS: elementary OS 6.1 Jólnir

I installed Beam today and found a bug where the first image loads but all others are the same.
![Screenshot from 2022-08-15 15 25 29](https://user-images.githubusercontent.com/93644977/184646255-f4369d89-a5ce-4f6d-bccc-961f50a0aef5.png)

After a restart it works fine again though

**Comment by simonv3** [comment]
@glottis0q thanks for the report! 

That's a known bug and we're not sure what's causing it. A previous report of it exists here https://github.com/resonatecoop/stream/issues/189

Most likely it's happening during playlist creation, or adding songs to a playlist.

**Comment by glottis0q** [comment]
Sry, I searched for issues with the keyword "image" but this one didn't show up

**Comment by simonv3** [comment]
You're good! It's in a different repo, and even a different organization from this one. Not your fault, I only know because I've puzzled over it :sweat_smile:
