### ISSUE TITLE
white screen on tapping search

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#56]
Mac OS / Big Sur

- opened app for the first time
- put cursor in search, saw dropdown
- white

- kill the app, try again
- this happens every time

<img width="1004" alt="Screen Shot 2022-04-23 at 7 37 33 AM" src="https://user-images.githubusercontent.com/2731744/164892856-24e23164-059b-456e-bd90-620e491494e3.png">

update:

stopped happening, now i can search

<img width="283" alt="Screen Shot 2022-04-23 at 7 49 01 AM" src="https://user-images.githubusercontent.com/2731744/164893251-7828e1cf-5755-4afe-9a7e-dc46bb03b12f.png">

**Comment by simonv3** [comment]
I think this is already fixed, @whatSocks can you confirm whether it works in the most recent dev build? I can also tag a new release if that's needed for testing.
