### ISSUE TITLE
mystery buttons on cover art

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#58]
<img width="465" alt="Screen Shot 2022-04-23 at 8 47 43 AM" src="https://user-images.githubusercontent.com/2731744/164895150-b0dfb96b-98d9-4333-aaee-3bf4f11e2919.png">

what do these do?

**Comment by whatSocks** [comment]
update: it's add to queue! maybe there should be an on-hover?

**Comment by simonv3** [comment]
yeah, the play button plays it, and the plus button adds it to the back of the queue. I wasn't sure what a good icon for that "add to back of the queue" would be. I've been using react-icons https://react-icons.github.io/react-icons/search so if there's something there that makes sense for that action let me know! We could also design a new one I guess! Curious what spotify uses if it uses something like this? It might just use text. 

A tooltip would work! Is there something that would work that would be more accessible for mobile devices than a tooltip?

**Comment by whatSocks** [comment]
I think the icon is fine, it's just only used there. 

How about changing "Your queue is empty :( Find some songs to play!" to 
"Your queue is empty :( 
Find some songs to play!
Tap the Add to Queue button to fill this list"

**Comment by simonv3** [comment]
It might also be a good idea to add a little snackbar that pops up when a task is complete.
