### ISSUE TITLE
releases, labels and artist pages are missing play & queue buttons

### ISSUE THREAD

**Issue by simonv3** [simonv3/beam#82]
![image](https://user-images.githubusercontent.com/485583/165114013-c852fe9f-7ec5-4080-bfc3-31e433a73bf2.png)

* [ ] Releases in Explore
* [ ] Releases on Artist Page
* [ ] Releases on Label Page

**Comment by whatSocks** [comment]
maybe related but when i go to view the release detail from the Explore > Release page I don't see the release

**Comment by simonv3** [comment]
Added the pages and fix for the above in #90.
