### ISSUE TITLE
Pressing play on a track in the queue will clear the queue

### ISSUE THREAD

**Issue by simonv3** [simonv3/beam#85]
1. Add a playlist to a queue
2. Go to the queue
3. Press any song in the playlist
4. Queue will clear

**Comment by whatSocks** [comment]
second step isn't needed:


    Add a playlist to a queue
    Press any song in the playlist
    Queue will clear (except for the 1 track playing)

**Comment by simonv3** [comment]
I think I fixed this by clearing the tracks in the queue prior to the newly pressed song but keeping the latter ones. Will be part of #90

**Comment by simonv3** [comment]
Oh wait I'm actually not sure that what you outlined above is fixed, need to double check.

**Comment by simonv3** [comment]
Okay, #92 addresses this
