### ISSUE TITLE
Background color should change on Dark Mode toggle

### ISSUE THREAD

**Issue by peterklingelhofer** [simonv3/beam#89]
<img width="1612" alt="Screen Shot 2022-04-25 at 6 12 24 PM" src="https://user-images.githubusercontent.com/60944077/165189357-2bf6a664-5112-4659-8745-822f37e7ae7d.png">
<img width="1612" alt="Screen Shot 2022-04-25 at 6 12 34 PM" src="https://user-images.githubusercontent.com/60944077/165189364-a00d88c5-3065-45e6-928f-a9d73d4e4f6a.png">

### Potential Solution
Modify the css file touched by #65

**Comment by simonv3** [comment]
We talked about implementing using theme functionality that comes with @emotion.
