### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by whatSocks** [simonv3/beam#95]
no idea what triggered this, I was trying to repro a bug then...

<img width="294" alt="Screen Shot 2022-04-26 at 5 54 52 PM" src="https://user-images.githubusercontent.com/2731744/165398900-3f3c1fb8-1ce0-4354-bb92-1f41b1ca0f17.png">

**Comment by simonv3** [comment]
There is no solution here, but maybe this is what's going on here too: 

https://github.com/brafdlog/caspion/issues/278

**Comment by peterklingelhofer** [comment]
Maybe we can avoid this error when I implement [purely React-based Dark Mode](https://github.com/simonv3/beam/issues/76), since we won't have have to do this "let's throw stuff on the window object business" anymore?

**Comment by simonv3** [comment]
Yeah, that would work!

**Comment by simonv3** [comment]
I put in a fix for this in the newest `main` branch if you want to try it out @whatSocks 

```
git pull origin main
yarn install
yarn electron:package:mac
```
